### ISSUE TITLE
.scn not loading

### ISSUE THREAD

**Issue by Muini** [CookieBadger/assetplacer-docs#10]
Hello!

Working with Scenes as .tscn works fine, but .scn seems not supported, nothing happen when drag & dropping them in the Asset browser library. Any reason for this limitation ? I have not found informations about it. Thanks!

For context, I work with .scn because it's faster as sub scenes from a blender file imports (break down multiple assets into their own scenes, very convinient to work with).

**Comment by CookieBadger** [comment]
Hello Muini, thanks for pointing this out too, while I was thinking of the .tres and .res files, when implementing meshes, I did not think of .scn files. This will also be fixed in the next version.
