### ISSUE TITLE
Suggestion, Support Editor Keymaps

### ISSUE THREAD

**Issue by eumario** [CookieBadger/assetplacer-docs#13]
I have started using a Recently released Addon called TerraBrush (https://github.com/spimort/terrabrush) which has the same Key Binding for G to it's tool as well.  I have suggested to them, and would also like to suggest to you as well, a way to add keymaps to the Editor Settings for Tool Shortcuts in the plugin, so that if there happens to be a conflict, the end user can change it.

Thanks.

**Comment by CookieBadger** [comment]
Hello Mario! 
You can actually change Assetplacer's keybindings already. Go to Project Settings (enable Advanced) and scroll to the bottom. In Assetplacer you will find a tab called "Shortcuts", where you can adjust all keys the plugin uses.

Happy Holidays!
