### ISSUE TITLE
[Request] Perspective angle 45°

### ISSUE THREAD

**Issue by maxime4000** [CookieBadger/assetplacer-docs#18]
So with the front perspective as default, some asset are hard to recognize because they are slim on the ground. With the naming request, the library is not really helpful. So I changed the settings to top perspective. It really better for my use case right now.

But I wonder if you could add a 45° perspective option? A perspective that you can view the top and the side of the assets. That way, wall, floor or props would have the perspective of "someone who is standing high in front of the object who's laying on the floor". You wouldn't have the best perspective for every item, but overall you would have a good perspective of most items.

**Comment by CookieBadger** [comment]
Hello @maxime4000, thank you for your suggestion. The feature has been added to 1.4.0, if you go under settings, you can now find a setting for a custom angle! 

Hope it helps :)
