### ISSUE TITLE
How do I migrate godot versions?

### ISSUE THREAD

**Issue by krazyjakee** [CookieBadger/assetplacer-docs#3]
I've hopped to `Godot_v4.1-beta1_mono_win64.exe` and now get the following on build...

```
Restoring packages for %AppData%\Local\Temp\NuGetScratch\acf8b69325f4410bb7efc21da9cd60b4\15d9695d31c2479a88ec76e8dbc45159.proj...
project.csproj(0,0): error : Unable to resolve 'Godot.NET.Sdk (= 4.1.0-beta.1)' for '.NETStandard,Version=v0.0'.
Project "project.csproj" (Restore target(s)):
	project.csproj(0,0): error MSB4236: The SDK 'Godot.NET.Sdk/4.1.0-beta.1' specified could not be found. [project.csproj]
```

This happens for any other version of Godot mono I install as well.

I'm guessing this requires some fiddling with nuget but I didn't have to do this to get set up so why is it requiring it now?

**Comment by CookieBadger** [comment]
Hey @krazyjakee sorry for replying so late, I thought I had replied to this. Could you solve your problem? 

I would guess that this is unrelated to the plugin, but just a Godot mono thing. I have personally no experience with Nuget.

**Comment by krazyjakee** [comment]
I'll do another check tomorrow. Although it seems like the Godot core team are late to upload new versions of the SDK to nuget, sometimes it will take several days.

I'm pretty confident that is the cause.

**Comment by CookieBadger** [comment]
Just tested in 4.1 stable and seems to work fine. Closing for now.
