### ISSUE TITLE
Asset's physical location and transform are different

### ISSUE THREAD

**Issue by Jeremandias** [CookieBadger/assetplacer-docs#5]
This might be an issue of my own, but when I place an asset, I see the physical model quite a ways from my mouse. The scene's transform location doesn't match it's visible location in the parent scene
<img width="508" alt="Screenshot 2023-06-25 191146" src="https://github.com/CookieBadger/assetplacer-docs/assets/78196942/45b52f83-3c1c-402e-b561-96e9e42f357f">
<img width="813" alt="Screenshot 2023-06-25 191101" src="https://github.com/CookieBadger/assetplacer-docs/assets/78196942/c8a5e651-1b52-4205-a5a8-e14e1f0e86a1">

**Comment by Jeremandias** [comment]
Seems to be an issue with the import

**Comment by CookieBadger** [comment]
This is a result of your asset being offset. If you open your asset's scene (what I figure to be the first screenshot) you need to make sure that the cube is at the origin if you want it to be placed on the mouse position with the plugin.

In case this is a 3D file (.obj, .fbx) and not a scene, then you apparently have an offset before you exported it (in Blender, Maya or whatever)
