### ISSUE TITLE
Fail to enable plugin

### ISSUE THREAD

**Issue by nigulavy** [CookieBadger/assetplacer-docs#7]
v4.1.1.stable.mono.official [bd6af8e0e]
.net SDK 7.0 or .net SDK 6.0
Error Message:
Unable to load addon script from path: 'res://addons/assetplacer/AssetPlacerPlugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/assetplacer/plugin.cfg' to prevent further errors.

**Comment by CookieBadger** [comment]
Unfortunately, I cannot say what the issue is for sure from that information. I suspect, that you forgot to build the Code (required for C# plugins). Please see the installation documentation for a walkthrough: https://cookiebadger.github.io/assetplacer-docs/installation.html

**Comment by nigulavy** [comment]
thanks for replay.
I have saw the installation guide carefully.
It's show me a error dialog as the attached image when I try to enble this
addon in the project settings.
[image: image.png]

More system info:
Window 11 x64
I have alos try the .net sdk 6 x64 and .net SDK 7 x64. the result is same
thanks

Tony Chen

CookieBadger ***@***.***> 于2023年8月18日周五 11:06写道：

**Comment by nigulavy** [comment]
When I try to enable this addon in the menu  project/project settings/Plugins, it popup an error dialog with text message: 
`Unable to load addon script from path: 'res://addons/assetplacer/AssetPlacerPlugin.cs'. This might be due to a code error in that script. Disabling the addon at 'res://addons/assetplacer/plugin.cfg' to prevent further errors.
`

**Following is the steps:**
1. Download the lastest version Godot: v4.1.1.stable.mono.official [bd6af8e0e]
2. Download the .net SDK 6.0 x64, and install it. Verify it with command: dotnet --info. It's good. And I also try the 7.0 .net SDK, it fail too.
3. Create a new project with default Render: Forward+
4. Create a new folder in the project res/addons
5.  Copy the addon code to projects folder: res/addons. 
6. The plugin "AssetPlacerPlugin" shows in the Project/Project Settings/Plugins. The status is unchecked.
7. Click the "Enable" button to check it. It shows an error dialog.

**The PC info:**
  HP Victus 
  CPU: 11th intel i5
  OS: Windows 11 x64
  GPU: NVIDIA GeForce RTX3050 Ti Laptop GPU

**Comment by CookieBadger** [comment]
After 5 you miss the build steps:
- Create a new C# script in your project and delete again.
- Press the "Build" Button in the top right corner of the Editor.
