### ISSUE TITLE
Half resolution viewport not working well

### ISSUE THREAD

**Issue by Muini** [CookieBadger/assetplacer-docs#9]
Hi! 
Small bug; I work on "Half Resolution" on my editor viewport for saving on battery life and performance. 
<img width="305" alt="image" src="https://github.com/CookieBadger/assetplacer-docs/assets/6160740/098418d1-ce8f-4250-be87-1461943cc615">
And this is breaking Asset placer coordinates, only a quarter of the viewport now reacts to the mouse and the coordinates are offset to this quarter.

**Comment by CookieBadger** [comment]
Hello Muini, thanks for pointing this out, I overlooked this feature when implementing the viewport input. It will be fixed in the next minor version!

**Comment by CookieBadger** [comment]
I noticed that tooltip placement might also be broken on half resolution, I have fixed it locally and will include the change in a future update. However, it will be a while, due to major refactoring.
